"""Canonical foundry contracts: the stable schema layer everything shares.

Import from here, not from the submodules, so internal layout can evolve:

    from foundry.contracts import Event, SystemBundle, MissionSpec, ...
"""

from ._util import (
    DIGEST_PREFIX,
    canonical_json,
    content_digest,
    is_digest,
    new_id,
    sha256_hex,
    utcnow,
)
from .bundle import BundleDiff, FieldChange, SignatureRecord, SystemBundle
from .enums import (
    ApprovalTier,
    AutonomyLevel,
    DecisionAction,
    GateId,
    MemoryType,
    MissionState,
    ModuleType,
    OperatingProfile,
    PromotionStatus,
    RiskClass,
    SecurityClass,
    TaskSetRole,
    VerificationStatus,
)
from .evaluation import EvaluationResult, MetricVector, ResultIntegrity, Uncertainty
from .events import (
    SCHEMA_VERSION,
    Event,
    EventTypes,
    Integrity,
    ModelRef,
    ModuleRef,
    ToolRef,
    Usage,
)
from .governance import (
    ApprovalRecord,
    CapabilityToken,
    DeploymentRecord,
    GateResult,
    PromotionDecision,
    RollbackRecord,
)
from .improvement import (
    ChangeTarget,
    DeploymentScope,
    ExperimentArm,
    ExperimentBudget,
    ExperimentRecord,
    ImprovementProposal,
    PairedAnalysis,
    Randomization,
    TaskSetRefs,
)
from .manifest import ModuleManifest, PermissionSpec, ResourceProfile, RetryPolicy
from .protocols import ArtifactStoreLike, LedgerLike, WorkerLike
from .memory import Confidence, ContextPackage, EvidenceItem, MemoryItem, MemoryLink, SourceRef
from .mission import (
    AcceptanceCriterion,
    Constraint,
    MissionRequest,
    MissionSpec,
    Objective,
    ResourceBudget,
)

__all__ = [
    "DIGEST_PREFIX",
    "SCHEMA_VERSION",
    "AcceptanceCriterion",
    "ArtifactStoreLike",
    "LedgerLike",
    "WorkerLike",
    "ApprovalRecord",
    "ApprovalTier",
    "AutonomyLevel",
    "BundleDiff",
    "CapabilityToken",
    "ChangeTarget",
    "Confidence",
    "Constraint",
    "ContextPackage",
    "DecisionAction",
    "DeploymentRecord",
    "DeploymentScope",
    "EvaluationResult",
    "Event",
    "EventTypes",
    "EvidenceItem",
    "ExperimentArm",
    "ExperimentBudget",
    "ExperimentRecord",
    "FieldChange",
    "GateId",
    "GateResult",
    "ImprovementProposal",
    "Integrity",
    "MemoryItem",
    "MemoryLink",
    "MemoryType",
    "MetricVector",
    "MissionRequest",
    "MissionSpec",
    "MissionState",
    "ModelRef",
    "ModuleManifest",
    "ModuleRef",
    "ModuleType",
    "Objective",
    "OperatingProfile",
    "PairedAnalysis",
    "PermissionSpec",
    "PromotionDecision",
    "PromotionStatus",
    "Randomization",
    "ResourceBudget",
    "ResourceProfile",
    "ResultIntegrity",
    "RetryPolicy",
    "RiskClass",
    "RollbackRecord",
    "SecurityClass",
    "SignatureRecord",
    "SourceRef",
    "SystemBundle",
    "TaskSetRefs",
    "TaskSetRole",
    "ToolRef",
    "Uncertainty",
    "Usage",
    "VerificationStatus",
    "canonical_json",
    "content_digest",
    "is_digest",
    "new_id",
    "sha256_hex",
    "utcnow",
]
