"""Deterministic coding-task corpus with executable-test oracles (report 18.3).

This is the Stage-1 step from string transformation to the report's actual
first domain: "small software tasks with executable tests". Each task is a
tiny repository (a buggy ``solution.py`` plus a ``checks.py`` assertion
script), an issue describing the defect, and a hidden ground-truth fix.
Success is decided by *running the checks*, not by string comparison, so
the oracle is the report 10.2 Deterministic Test Service in miniature.

Two bug families create the measurable naive-vs-robust gap the paired
experiments need (mirroring the slugify corpus):

* ``boundary``   -- an off-by-one loop bound (``range(n)`` for an inclusive
  sum). Both repair strategies fix this family.
* ``comparison`` -- an exclusive ``>`` where the contract requires the
  threshold value itself to pass. Only the robust strategy fixes this.

Roles follow report 13.4/18.3: ``development`` mixes both families,
``protected`` is comparison-heavy and disjoint from development,
``retention`` contains only boundary tasks the naive strategy already
solves (non-inferiority evidence), and ``adversarial`` embeds the
comparison bug in files with unicode content and CRLF line endings, so a
repair that rewrites the file instead of editing the defect breaks the
integrity assertions.

Everything is generated by construction from ``(seed, index)`` -- no
randomness at all -- so corpora are bit-identical across platforms and
interpreter versions.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from dataclasses import dataclass, field
from types import MappingProxyType

SOLUTION_FILE = "solution.py"
CHECKS_FILE = "checks.py"

#: Exact buggy/fixed line pairs shared with the repair strategies in
#: :mod:`foundry.workers.coding_worker`; generation and repair agreeing on
#: these strings is what makes the robust strategy ground-truth-capable.
BOUNDARY_BUG = "for value in range(n):"
BOUNDARY_FIX = "for value in range(n + 1):"
COMPARISON_BUG = " > "
COMPARISON_FIX = " >= "


@dataclass(frozen=True)
class CodingTask:
    """One executable coding task. ``fixed_files`` is the hidden ground truth."""

    task_id: str
    family: str  # "boundary" | "comparison"
    difficulty: str  # "easy" | "hard" | "adversarial"
    issue: str
    files: Mapping[str, str] = field(default_factory=dict)
    fixed_files: Mapping[str, str] = field(default_factory=dict)

    @property
    def input_text(self) -> str:
        """Candidate-visible serialization: the issue and the buggy repo.

        This is what the holdout vault exposes through ``BlindTaskView``
        and what leakage checks scan; ``fixed_files`` is deliberately not
        part of it (ground truth never crosses the vault boundary).
        """
        return json.dumps(
            {"issue": self.issue, "files": dict(self.files)},
            sort_keys=True,
            ensure_ascii=False,
        )


def _freeze(files: dict[str, str]) -> Mapping[str, str]:
    return MappingProxyType(files)


def _boundary_task(seed: int, index: int, *, difficulty: str = "easy") -> CodingTask:
    fn = f"total_through_v{index}"
    k = 4 + 3 * index + (seed % 7)
    right = k * (k + 1) // 2
    wrong = k * (k - 1) // 2
    buggy_solution = (
        f"def {fn}(n):\n"
        f'    """Sum of the integers from 0 through n, inclusive of n itself."""\n'
        f"    total = 0\n"
        f"    {BOUNDARY_BUG}\n"
        f"        total += value\n"
        f"    return total\n"
    )
    checks = (
        f"from solution import {fn}\n"
        f"\n"
        f'assert {fn}({k}) == {right}, "inclusive sum of 0..{k} must be {right}"\n'
        f'assert {fn}(0) == 0, "sum through 0 is 0"\n'
        f'print("checks passed")\n'
    )
    issue = (
        f"`{fn}` documents an inclusive upper bound, but `{fn}({k})` returns "
        f"{wrong} instead of {right}. Fix the off-by-one loop boundary."
    )
    files = {SOLUTION_FILE: buggy_solution, CHECKS_FILE: checks}
    fixed = dict(files)
    fixed[SOLUTION_FILE] = buggy_solution.replace(BOUNDARY_BUG, BOUNDARY_FIX, 1)
    return CodingTask(
        task_id=f"code-boundary-{seed}-{index}",
        family="boundary",
        difficulty=difficulty,
        issue=issue,
        files=_freeze(files),
        fixed_files=_freeze(fixed),
    )


def _comparison_source(fn: str, threshold: int) -> str:
    return (
        f"def {fn}(value):\n"
        f'    """Return True when value meets or exceeds the threshold of {threshold}."""\n'
        f"    return value{COMPARISON_BUG}{threshold}\n"
    )


def _comparison_checks(fn: str, threshold: int, extra: str = "") -> str:
    return (
        f"from solution import {fn}\n"
        f"{extra}"
        f"\n"
        f'assert {fn}({threshold}) is True, "the threshold value itself must pass"\n'
        f'assert {fn}({threshold - 1}) is False, "below threshold must fail"\n'
        f'assert {fn}({threshold + 1}) is True, "above threshold must pass"\n'
        f'print("checks passed")\n'
    )


def _comparison_issue(fn: str, threshold: int) -> str:
    return (
        f"`{fn}` must accept the threshold value {threshold} itself, but "
        f"`{fn}({threshold})` returns False. The threshold comparison is "
        f"exclusive; make it inclusive without touching anything else."
    )


def _comparison_task(seed: int, index: int) -> CodingTask:
    fn = f"meets_threshold_v{index}"
    threshold = 10 + 2 * index + (seed % 5)
    buggy_solution = _comparison_source(fn, threshold)
    files = {SOLUTION_FILE: buggy_solution, CHECKS_FILE: _comparison_checks(fn, threshold)}
    fixed = dict(files)
    fixed[SOLUTION_FILE] = buggy_solution.replace(COMPARISON_BUG, COMPARISON_FIX, 1)
    return CodingTask(
        task_id=f"code-comparison-{seed}-{index}",
        family="comparison",
        difficulty="hard",
        issue=_comparison_issue(fn, threshold),
        files=_freeze(files),
        fixed_files=_freeze(fixed),
    )


#: Unicode canary embedded in adversarial files: a repair that rewrites or
#: re-encodes the file instead of editing the defect breaks this assertion.
UNICODE_CANARY = '안녕 — ünïcode ✓'


def _adversarial_task(seed: int, index: int) -> CodingTask:
    fn = f"gate_open_v{index}"
    threshold = 20 + 2 * index + (seed % 5)
    buggy_solution = (
        f'GREETING = "{UNICODE_CANARY}"\n'
        f"\n" + _comparison_source(fn, threshold)
    ).replace("\n", "\r\n")  # CRLF: a sloppy rewrite normalizes and detects itself
    extra = (
        f"import solution\n"
        f'assert solution.GREETING == "{UNICODE_CANARY}", "file content was corrupted"\n'
        f'assert "\\r\\n" in open("solution.py", newline="", encoding="utf-8").read(), '
        f'"line endings were rewritten"\n'
    )
    checks = _comparison_checks(fn, threshold, extra=extra)
    files = {SOLUTION_FILE: buggy_solution, CHECKS_FILE: checks}
    fixed = dict(files)
    fixed[SOLUTION_FILE] = buggy_solution.replace(COMPARISON_BUG, COMPARISON_FIX, 1)
    return CodingTask(
        task_id=f"code-adversarial-{seed}-{index}",
        family="comparison",
        difficulty="adversarial",
        issue=_comparison_issue(fn, threshold),
        files=_freeze(files),
        fixed_files=_freeze(fixed),
    )


def generate_coding_task_sets(seed: int) -> dict[str, list[CodingTask]]:
    """Four-role coding corpus, deterministic by construction.

    Index ranges per role do not overlap, so roles are disjoint for any
    seed (protected tasks are never a rehash of development tasks).
    """
    return {
        "development": (
            [_boundary_task(seed, i) for i in range(4)]
            + [_comparison_task(seed, i) for i in range(4)]
        ),
        "protected": [_comparison_task(seed, 100 + i) for i in range(6)],
        "retention": [_boundary_task(seed, 200 + i, difficulty="easy") for i in range(4)],
        "adversarial": [_adversarial_task(seed, 300 + i) for i in range(3)],
    }
